#!/usr/bin/ruby

require 'monotonic_time'
require './common'
require '../lib/sorted_array_binary'

ar = make_array_with_random_numbers 10000
sec = MonotonicTime.measure { ar.sort }
say 'sorting', sec

sec = MonotonicTime.measure {
  sa = SortedArrayBinary.new
  sa.push *ar
}
say 'pushing into SortedArray', sec

sec = MonotonicTime.measure {
  SortedArrayBinary.new ar
}
say 'SortedArray.new', sec
