#!/usr/bin/ruby

require 'monotonic_time'
require 'sorted_array'
require 'array-sorted'
require './common'
require '../lib/sorted_array_binary'

def measure sorted_array_name, sorted_array_instance
  sec = MonotonicTime.measure {
    @ar.each { |el|
      sorted_array_instance.push el
    }
  }
  say sorted_array_name, sec
end

measure 'sorted_array',
  SortedArray::SortedArray.new(SortedArray::DefaultSorter.new(:to_i))
measure 'array-sorted', Array::Sorted.new
measure 'sorted_array_binary', SortedArrayBinary.new
